import type { User } from '@supabase/supabase-js';
import type { Profile } from '@/shared/types/database';
import type { Trade } from '@/features/journal/hooks/useTrades';
import type { TradingAccount } from '@/features/dashboard/hooks/useTradingAccounts';

// ─────────────────────────────────────────────────────────────
// Guest pseudo-user (never sent to Supabase)
// ─────────────────────────────────────────────────────────────
export const GUEST_MOCK_USER: User = {
  id: 'guest',
  aud: 'authenticated',
  role: 'authenticated',
  email: 'guest@demo.com',
  email_confirmed_at: new Date().toISOString(),
  phone: '',
  confirmed_at: new Date().toISOString(),
  last_sign_in_at: new Date().toISOString(),
  app_metadata: {},
  user_metadata: { full_name: 'Demo Trader' },
  identities: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  is_anonymous: true,
  factors: [],
};

export const GUEST_MOCK_PROFILE: Profile = {
  id: 'guest',
  email: 'guest@demo.com',
  full_name: 'Demo Trader',
  avatar_url: null,
  subscription_plan: 'free',
  subscription_expires_at: null,
  timezone: 'America/Buenos_Aires',
  currency: 'USD',
  role: 'user',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const GUEST_MOCK_ACCOUNT: TradingAccount = {
  id: 'guest-account',
  user_id: 'guest',
  name: 'Demo Account',
  broker: 'Demo Broker',
  account_type: 'demo',
  initial_balance: 10000,
  current_balance: 11340,
  currency: 'USD',
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// ─────────────────────────────────────────────────────────────
// Helpers to build relative dates
// ─────────────────────────────────────────────────────────────
function daysAgo(n: number, hourOffset = 9): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hourOffset, 0, 0, 0);
  return d.toISOString();
}

// ─────────────────────────────────────────────────────────────
// 15 demo trades – realistic mix of wins/losses
// ─────────────────────────────────────────────────────────────
export const GUEST_MOCK_TRADES: Trade[] = [
  {
    id: 'g-t-01', user_id: 'guest', account_id: 'guest-account',
    symbol: 'EUR/USD', asset_class: 'forex', direction: 'long', status: 'closed',
    entry_price: 1.0850, exit_price: 1.0920, quantity: 1,
    stop_loss: 1.0800, take_profit: 1.0950,
    entry_date: daysAgo(30, 9), exit_date: daysAgo(30, 14),
    pnl: 280, pnl_percentage: 2.8, commission: 7, swap: 0,
    timeframe: '1H', strategy: 'Breakout', setup_type: 'Breakout',
    notes: 'Clean break of resistance', tags: ['breakout', 'trend'], rating: 4,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(30), updated_at: daysAgo(30),
  },
  {
    id: 'g-t-02', user_id: 'guest', account_id: 'guest-account',
    symbol: 'GBP/USD', asset_class: 'forex', direction: 'short', status: 'closed',
    entry_price: 1.2700, exit_price: 1.2640, quantity: 1,
    stop_loss: 1.2750, take_profit: 1.2600,
    entry_date: daysAgo(28, 10), exit_date: daysAgo(27, 16),
    pnl: 240, pnl_percentage: 2.4, commission: 7, swap: -2,
    timeframe: '4H', strategy: 'Trend Following', setup_type: 'Pullback',
    notes: 'Trend continuation, good R:R', tags: ['trend'], rating: 5,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(28), updated_at: daysAgo(27),
  },
  {
    id: 'g-t-03', user_id: 'guest', account_id: 'guest-account',
    symbol: 'BTC/USD', asset_class: 'crypto', direction: 'long', status: 'closed',
    entry_price: 68500, exit_price: 67200, quantity: 0.05,
    stop_loss: 67000, take_profit: 71000,
    entry_date: daysAgo(25, 14), exit_date: daysAgo(24, 11),
    pnl: -65, pnl_percentage: -1.3, commission: 4, swap: 0,
    timeframe: '1D', strategy: 'Support/Resistance', setup_type: 'Bounce',
    notes: 'Hit stop, market was choppy', tags: ['loss', 'crypto'], rating: 2,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(25), updated_at: daysAgo(24),
  },
  {
    id: 'g-t-04', user_id: 'guest', account_id: 'guest-account',
    symbol: 'AAPL', asset_class: 'stocks', direction: 'long', status: 'closed',
    entry_price: 195.50, exit_price: 201.20, quantity: 10,
    stop_loss: 192.00, take_profit: 204.00,
    entry_date: daysAgo(22, 9), exit_date: daysAgo(20, 15),
    pnl: 570, pnl_percentage: 5.7, commission: 10, swap: 0,
    timeframe: '1D', strategy: 'Earnings Play', setup_type: 'Momentum',
    notes: 'Strong earnings beat', tags: ['stocks', 'earnings'], rating: 5,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(22), updated_at: daysAgo(20),
  },
  {
    id: 'g-t-05', user_id: 'guest', account_id: 'guest-account',
    symbol: 'USD/JPY', asset_class: 'forex', direction: 'long', status: 'closed',
    entry_price: 149.80, exit_price: 150.60, quantity: 1,
    stop_loss: 149.20, take_profit: 151.00,
    entry_date: daysAgo(20, 8), exit_date: daysAgo(19, 16),
    pnl: 160, pnl_percentage: 1.6, commission: 7, swap: 3,
    timeframe: '1H', strategy: 'Breakout', setup_type: 'Breakout',
    notes: 'Yen weakness persisting', tags: ['forex', 'yen'], rating: 4,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(20), updated_at: daysAgo(19),
  },
  {
    id: 'g-t-06', user_id: 'guest', account_id: 'guest-account',
    symbol: 'ETH/USD', asset_class: 'crypto', direction: 'short', status: 'closed',
    entry_price: 3450, exit_price: 3290, quantity: 0.3,
    stop_loss: 3550, take_profit: 3200,
    entry_date: daysAgo(18, 11), exit_date: daysAgo(17, 9),
    pnl: 480, pnl_percentage: 4.8, commission: 6, swap: 0,
    timeframe: '4H', strategy: 'Short Squeeze Fade', setup_type: 'Reversal',
    notes: 'Overbought on RSI, clean short', tags: ['crypto', 'short'], rating: 4,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(18), updated_at: daysAgo(17),
  },
  {
    id: 'g-t-07', user_id: 'guest', account_id: 'guest-account',
    symbol: 'EUR/GBP', asset_class: 'forex', direction: 'short', status: 'closed',
    entry_price: 0.8580, exit_price: 0.8620, quantity: 1,
    stop_loss: 0.8550, take_profit: 0.8520,
    entry_date: daysAgo(16, 9), exit_date: daysAgo(15, 14),
    pnl: -100, pnl_percentage: -1.0, commission: 7, swap: -1,
    timeframe: '1H', strategy: 'Range Trading', setup_type: 'Mean Reversion',
    notes: 'Bad timing, news spike', tags: ['loss', 'forex'], rating: 2,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(16), updated_at: daysAgo(15),
  },
  {
    id: 'g-t-08', user_id: 'guest', account_id: 'guest-account',
    symbol: 'TSLA', asset_class: 'stocks', direction: 'long', status: 'closed',
    entry_price: 248.00, exit_price: 256.50, quantity: 8,
    stop_loss: 242.00, take_profit: 262.00,
    entry_date: daysAgo(14, 10), exit_date: daysAgo(12, 15),
    pnl: 680, pnl_percentage: 6.8, commission: 10, swap: 0,
    timeframe: '1D', strategy: 'Momentum', setup_type: 'Momentum',
    notes: 'Strong volume breakout', tags: ['stocks', 'momentum'], rating: 5,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(14), updated_at: daysAgo(12),
  },
  {
    id: 'g-t-09', user_id: 'guest', account_id: 'guest-account',
    symbol: 'XAU/USD', asset_class: 'commodities', direction: 'long', status: 'closed',
    entry_price: 2310, exit_price: 2295, quantity: 0.1,
    stop_loss: 2290, take_profit: 2350,
    entry_date: daysAgo(11, 8), exit_date: daysAgo(10, 12),
    pnl: -150, pnl_percentage: -1.5, commission: 8, swap: -2,
    timeframe: '4H', strategy: 'Support/Resistance', setup_type: 'Bounce',
    notes: 'Dollar strength surprised', tags: ['gold', 'loss'], rating: 3,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(11), updated_at: daysAgo(10),
  },
  {
    id: 'g-t-10', user_id: 'guest', account_id: 'guest-account',
    symbol: 'NAS100', asset_class: 'futures', direction: 'long', status: 'closed',
    entry_price: 19200, exit_price: 19450, quantity: 1,
    stop_loss: 19050, take_profit: 19600,
    entry_date: daysAgo(9, 9), exit_date: daysAgo(8, 14),
    pnl: 250, pnl_percentage: 2.5, commission: 12, swap: 0,
    timeframe: '1H', strategy: 'Trend Following', setup_type: 'Pullback',
    notes: 'CPI data came in cool', tags: ['index', 'macro'], rating: 4,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(9), updated_at: daysAgo(8),
  },
  {
    id: 'g-t-11', user_id: 'guest', account_id: 'guest-account',
    symbol: 'AUD/USD', asset_class: 'forex', direction: 'short', status: 'closed',
    entry_price: 0.6580, exit_price: 0.6520, quantity: 1,
    stop_loss: 0.6620, take_profit: 0.6480,
    entry_date: daysAgo(7, 10), exit_date: daysAgo(6, 16),
    pnl: 120, pnl_percentage: 1.2, commission: 7, swap: 1,
    timeframe: '4H', strategy: 'Trend Following', setup_type: 'Pullback',
    notes: 'Weak Aus jobs data', tags: ['forex', 'short'], rating: 4,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(7), updated_at: daysAgo(6),
  },
  {
    id: 'g-t-12', user_id: 'guest', account_id: 'guest-account',
    symbol: 'SPX500', asset_class: 'futures', direction: 'long', status: 'closed',
    entry_price: 5200, exit_price: 5185, quantity: 1,
    stop_loss: 5175, take_profit: 5250,
    entry_date: daysAgo(5, 9), exit_date: daysAgo(4, 14),
    pnl: -150, pnl_percentage: -1.5, commission: 12, swap: 0,
    timeframe: '1H', strategy: 'Support/Resistance', setup_type: 'Bounce',
    notes: 'Fed speaker was hawkish', tags: ['index', 'loss'], rating: 2,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(5), updated_at: daysAgo(4),
  },
  {
    id: 'g-t-13', user_id: 'guest', account_id: 'guest-account',
    symbol: 'EUR/USD', asset_class: 'forex', direction: 'long', status: 'closed',
    entry_price: 1.0780, exit_price: 1.0840, quantity: 1,
    stop_loss: 1.0740, take_profit: 1.0880,
    entry_date: daysAgo(4, 8), exit_date: daysAgo(3, 12),
    pnl: 240, pnl_percentage: 2.4, commission: 7, swap: 0,
    timeframe: '1H', strategy: 'Breakout', setup_type: 'Breakout',
    notes: 'Clean break after consolidation', tags: ['forex', 'breakout'], rating: 5,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(4), updated_at: daysAgo(3),
  },
  {
    id: 'g-t-14', user_id: 'guest', account_id: 'guest-account',
    symbol: 'BTC/USD', asset_class: 'crypto', direction: 'long', status: 'closed',
    entry_price: 69800, exit_price: 71200, quantity: 0.04,
    stop_loss: 68800, take_profit: 72000,
    entry_date: daysAgo(2, 14), exit_date: daysAgo(1, 10),
    pnl: 560, pnl_percentage: 5.6, commission: 4, swap: 0,
    timeframe: '4H', strategy: 'Momentum', setup_type: 'Momentum',
    notes: 'ETF inflows driving price', tags: ['crypto', 'momentum'], rating: 5,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(2), updated_at: daysAgo(1),
  },
  {
    id: 'g-t-15', user_id: 'guest', account_id: 'guest-account',
    symbol: 'GBP/JPY', asset_class: 'forex', direction: 'long', status: 'open',
    entry_price: 193.50, exit_price: null, quantity: 1,
    stop_loss: 192.00, take_profit: 196.00,
    entry_date: daysAgo(0, 9), exit_date: null,
    pnl: null, pnl_percentage: null, commission: 7, swap: 0,
    timeframe: '1H', strategy: 'Trend Following', setup_type: 'Pullback',
    notes: 'Waiting for target', tags: ['forex', 'open'], rating: null,
    stop_size: null, import_row_hash: null,
    created_at: daysAgo(0), updated_at: daysAgo(0),
  },
];
